version: '3.5'
services:
  db:
    image: gabrielpontes/tech-challenge-db:v1.0.6
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - tech-challenge-network
volumes:
  db-volume:
networks:
  tech-challenge-network:
    driver: bridge
